### ISSUE TITLE
why sendBuf() need time.Sleep()?

### ISSUE THREAD

**Issue by leanang** [xfxdev/xtcp#1]
Hi,
The sendBuf() function will sleep when the RawConn.Write() return error.  Why? I'm getting confused.  
What error will RawConn.Write() return when sendBuf write data?

**Comment by xfxdev** [comment]
Because want to distinguish transient network errors from permanent ones, and only will sleep if the return error is temporary.

Same error handling both in read and write
https://github.com/xfxdev/xtcp/blob/master/xconn.go#L95
https://github.com/xfxdev/xtcp/blob/master/xconn.go#L153
